### ISSUE TITLE
Add emmet support

### ISSUE THREAD

**Issue by watzon** [duyluonglc/vscode-edge#2]
I believe you can add emmet support just by changing the syntax file around a bit so that emmet sees it as HTML. [This](https://github.com/Microsoft/vscode/blob/master/extensions/emmet/src/util.ts) is the part of the emmet code that decides which syntaxes are supported.

**Comment by duyluonglc** [comment]
Try to add this to User Setting
```json
  "emmet.includeLanguages": {
    "edge": "html"
  }
```

**Comment by watzon** [comment]
Thanks for that!
