### ISSUE TITLE
@each vs @endeach

### ISSUE THREAD

**Issue by cgilmore** [duyluonglc/vscode-edge#5]
Should the `@each` blocks end with `@endeach` rather than `@each`?

https://github.com/duyluonglc/vscode-edge/blob/e5c6d9889c19fa3f04eb0e647667d17996f04fe6/snippets/snippets.json#L79

I otherwise get the error:

> E_UNCLOSED_TAG: Unclosed (each) tag found as < @each> statement. Make sure to close it as (endeach)

**Comment by duyluonglc** [comment]
@sikthought 
check v0.2
