### ISSUE TITLE
Syntax Highlighting Within HTML Attributes

### ISSUE THREAD

**Issue by cgilmore** [duyluonglc/vscode-edge#6]
When using dynamic blocks within an attribute (inside the quotes, `""`), the block takes on the scope of an HTML string, specifically `string.quoted.double.html`. For example:

```
<input value="{{ old('title', '') }}">
```

The block inside the value attribute, `{{ old('title', '') }}`, is all the same color, as if it were a string.

I've attached an image that shows how it's rendered in VSCode (on top) and in Sublime (on bottom).

<img width="667" alt="code example of Edge syntax coloring comparing VSCode and Sublime" src="https://user-images.githubusercontent.com/17103088/38182646-89e3b3dc-3600-11e8-89c1-1a51cee0d19a.png">

I know these examples use Adonis specific view helpers but thought I could use them as an example of the issue.

Thanks!

**Comment by duyluonglc** [comment]
@sikthought check v0.2

**Comment by cgilmore** [comment]
Awesome!
